import "server-only";
import { getDb } from "./db";
import { computePathConfidence } from "./confidence";
import type { Edge, NodeType, Organization } from "./types";
import { nodeKey } from "./types";

export interface PathNodeRef {
  type: NodeType;
  id: number;
}

export interface FoundPath {
  nodes: PathNodeRef[];
  edges: Edge[];
  edgeConfidences: number[];
  pathConfidence: number;
  hopCount: number;
  targetOrgId: number;
}

export interface FindPathsOptions {
  materialTag?: string | null;
  region?: string | null;
  consentedOnly?: boolean;
  limit?: number;
  excludeTargetIds?: number[];
  // Restrict candidate targets to these org kinds (default supplier + facility).
  targetKinds?: string[];
}

interface Graph {
  adj: Map<string, { to: string; edge: Edge }[]>;
  edgeById: Map<number, Edge>;
}

// Floor confidence so weights stay finite; -log(conf) makes additive Dijkstra
// minimise exactly what we rank on — the MULTIPLICATIVE path confidence — so the
// shortest path is the highest-confidence path. (1/conf would not preserve that.)
function weight(conf: number): number {
  const c = Math.max(conf, 1) / 100;
  return -Math.log(c);
}

function parseKey(key: string): PathNodeRef {
  const [type, id] = key.split(":");
  return { type: type as NodeType, id: Number(id) };
}

function buildGraph(consentedOnly: boolean): Graph {
  const db = getDb();
  const rows = db.prepare("SELECT * FROM edges").all() as Edge[];
  const adj = new Map<string, { to: string; edge: Edge }[]>();
  const edgeById = new Map<number, Edge>();
  for (const e of rows) {
    if (consentedOnly && e.consent_status !== "double_opt_in") continue;
    edgeById.set(e.id, e);
    const a = nodeKey(e.source_type, e.source_id);
    const b = nodeKey(e.target_type, e.target_id);
    if (!adj.has(a)) adj.set(a, []);
    if (!adj.has(b)) adj.set(b, []);
    adj.get(a)!.push({ to: b, edge: e });
    adj.get(b)!.push({ to: a, edge: e }); // relationships are navigable both ways
  }
  return { adj, edgeById };
}

interface DijkstraResult {
  nodeKeys: string[];
  edges: Edge[];
  cost: number;
}

// Strongest available (highest-confidence) edge between two node keys.
function strongestEdge(graph: Graph, a: string, b: string): Edge | null {
  const list = graph.adj.get(a);
  if (!list) return null;
  let best: Edge | null = null;
  for (const { to, edge } of list) {
    if (to === b && (!best || edge.confidence > best.confidence)) best = edge;
  }
  return best;
}

function dijkstra(
  graph: Graph,
  source: string,
  target: string,
  blockedEdgeIds: Set<number>,
  blockedNodes: Set<string>
): DijkstraResult | null {
  const dist = new Map<string, number>();
  const prev = new Map<string, { node: string; edge: Edge }>();
  const visited = new Set<string>();
  dist.set(source, 0);

  while (true) {
    // Pick the unvisited node with the smallest tentative distance (small graph).
    let u: string | null = null;
    let best = Infinity;
    for (const [node, d] of dist) {
      if (!visited.has(node) && d < best) {
        best = d;
        u = node;
      }
    }
    if (u === null) break;
    if (u === target) break;
    visited.add(u);

    const neighbors = graph.adj.get(u) ?? [];
    for (const { to, edge } of neighbors) {
      if (blockedEdgeIds.has(edge.id)) continue;
      if (to !== target && blockedNodes.has(to)) continue;
      if (to === source) continue;
      const nd = (dist.get(u) ?? Infinity) + weight(edge.confidence);
      if (nd < (dist.get(to) ?? Infinity)) {
        dist.set(to, nd);
        prev.set(to, { node: u, edge });
      }
    }
  }

  if (!dist.has(target) || !prev.has(target)) {
    return source === target ? { nodeKeys: [source], edges: [], cost: 0 } : null;
  }

  const nodeKeys: string[] = [];
  const edges: Edge[] = [];
  let cur = target;
  while (cur !== source) {
    const p = prev.get(cur);
    if (!p) return null;
    nodeKeys.unshift(cur);
    edges.unshift(p.edge);
    cur = p.node;
  }
  nodeKeys.unshift(source);
  return { nodeKeys, edges, cost: dist.get(target) ?? Infinity };
}

// Best path plus a few alternates, generated by removing one edge of the best
// path at a time (the first expansion of Yen's k-shortest-paths algorithm).
function pathsToTarget(
  graph: Graph,
  source: string,
  target: string,
  n: number
): DijkstraResult[] {
  const best = dijkstra(graph, source, target, new Set(), new Set());
  if (!best || best.edges.length === 0) return [];
  const results: DijkstraResult[] = [best];
  const seen = new Set<string>([best.nodeKeys.join(">")]);

  for (const edge of best.edges) {
    if (results.length >= n) break;
    const alt = dijkstra(graph, source, target, new Set([edge.id]), new Set());
    if (!alt || alt.edges.length === 0) continue;
    const sig = alt.nodeKeys.join(">");
    if (seen.has(sig)) continue;
    seen.add(sig);
    results.push(alt);
  }
  return results;
}

function matchesTag(org: Organization, tag: string): boolean {
  const t = tag.toLowerCase().trim();
  if (!t) return true;
  const hay = [...org.materials, ...org.capabilities].map((s) =>
    s.toLowerCase()
  );
  return hay.some((s) => s.includes(t) || t.includes(s));
}

function rowToOrg(r: any): Organization {
  return {
    ...r,
    materials: JSON.parse(r.materials || "[]"),
    capabilities: JSON.parse(r.capabilities || "[]"),
  };
}

export function findPaths(
  source: PathNodeRef,
  options: FindPathsOptions = {}
): FoundPath[] {
  const {
    materialTag = null,
    region = null,
    consentedOnly = false,
    limit = 5,
    excludeTargetIds = [],
    targetKinds = ["supplier", "facility"],
  } = options;

  const db = getDb();
  const graph = buildGraph(consentedOnly);
  const sourceKey = nodeKey(source.type, source.id);

  // Candidate target orgs: right kind + tag match (+ region preference).
  const allOrgs = (
    db.prepare("SELECT * FROM organizations").all() as any[]
  ).map(rowToOrg);
  let candidates = allOrgs.filter(
    (o) =>
      targetKinds.includes(o.kind) &&
      !excludeTargetIds.includes(o.id) &&
      (materialTag ? matchesTag(o, materialTag) : true)
  );
  if (region) {
    const inRegion = candidates.filter(
      (o) => (o.region || "").toLowerCase() === region.toLowerCase()
    );
    if (inRegion.length) candidates = inRegion;
  }

  const found: FoundPath[] = [];
  const seenSignatures = new Set<string>();

  for (const target of candidates) {
    const targetKey = nodeKey("org", target.id);
    if (targetKey === sourceKey) continue;
    const paths = pathsToTarget(graph, sourceKey, targetKey, 2);
    for (const p of paths) {
      const sig = p.nodeKeys.join(">");
      if (seenSignatures.has(sig)) continue;
      seenSignatures.add(sig);
      const edgeConfidences = p.edges.map((e) => e.confidence);
      found.push({
        nodes: p.nodeKeys.map(parseKey),
        edges: p.edges,
        edgeConfidences,
        pathConfidence: computePathConfidence(edgeConfidences),
        hopCount: p.edges.length,
        targetOrgId: target.id,
      });
    }
  }

  found.sort(
    (a, b) =>
      b.pathConfidence - a.pathConfidence || a.hopCount - b.hopCount
  );
  return found.slice(0, limit);
}
